services:
    advertising_source.manager:
        class: Realtor\DictionaryBundle\Manager\AdvertisingSourceManager
        arguments: ["@doctrine.orm.entity_manager"]
    branches.manager:
        class: Realtor\DictionaryBundle\Manager\BranchesManager
        arguments: ["@doctrine.orm.entity_manager"]
    users.manager:
        class: Realtor\UserBundle\Manager\UsersManager
        arguments: ["@doctrine.orm.entity_manager"]